### ISSUE TITLE
org-mode模式下，item换行切换输入法的问题

### ISSUE THREAD

**Issue by kidoln** [laishulu/emacs-smart-input-source#10]
在org-mode模式下，中文输入法，+或- 作为itemize在行首，如果按ctrl+换行（自动插入+/-），会切换到英文输入法。按照使用习惯，这里应该保持原有的输入法不变。

**Comment by laishulu** [comment]
>如果按ctrl+换行（自动插入+/-），会切换到英文输入法。

请描述清楚<kbd>ctrl+换行</kbd>是什么意思，
是指<kbd>ctrl+enter</kbd>么？

我这里的org-mode，这么按跟普通回车是一样的。也不会自动插入 `+/-`

从设计上来讲，不会自动切到英文的。

**Comment by kidoln** [comment]
是的。ctrl+enter 或者 mac+enter，都会在新的一行头上插入一个“+”。我是在mac os 10.15，doom emacs 环境下，使用org-roam。具体版本如下。中文使用的搜狗输入法，配置都是用缺省的。

GNU Emacs 26.3 (build 1, x86_64-apple-darwin19.5.0, Carbon Version 162 AppKit 1894.5) of 2020-06-23

**Comment by laishulu** [comment]
我也是doom emacs macos 10.15

org-roam 是自己装的包么？doom自带的我只看到org

能否把你对这个包的配置也共享一下。

**Comment by kidoln** [comment]
就是用这个链接上，doom部分的安装方法。https://org-roam.readthedocs.io/en/master/installation/

**Comment by laishulu** [comment]
哦，那doom自带的就是那个。

但是我打开一个org文件，编辑的时候，并没有这个快捷键啊。

**Comment by kidoln** [comment]
可以看一下这个链接，这个行为跟我现在的一致。但是我并没有什么特别的配置。https://emacs.stackexchange.com/questions/51117/org-mode-control-whether-m-ret-inserts-a-newline-or-not-for-plain-lists

**Comment by laishulu** [comment]
哦哦哦。。

等一下。。有这个flag`roam`

**Comment by laishulu** [comment]
我刚才又看了，最新版的doom没有这个。。。。
<img width="504" alt="图片" src="https://user-images.githubusercontent.com/1224321/87018752-43b7d400-c204-11ea-9dc6-faeb2657bd69.png">

**Comment by laishulu** [comment]
不行我手工装一下吧。

**Comment by kidoln** [comment]
![image](https://user-images.githubusercontent.com/886552/87018828-5f22df00-c204-11ea-86a7-0fc44e3f3810.png)
这样配置不行，是吗？

**Comment by laishulu** [comment]
你后来给我的链接。。。。
发现是：<kbd>M-enter</kbd>
这个可以

你之前给的是<kbd>C-enter</kbd>

**Comment by kidoln** [comment]
我这边，两个都可以。我也不知道为什么。

**Comment by laishulu** [comment]
但是，我试了

中文输入法不变啊。。

**Comment by kidoln** [comment]
呃，那怎么回事呢？我把配置改一改，自己试试。

**Comment by laishulu** [comment]
不过，我这里就是doom，没有roam。

**Comment by laishulu** [comment]
![2020-07-09 16-55-38 2020-07-09 16_56_14](https://user-images.githubusercontent.com/1224321/87019507-4961e980-c205-11ea-9ac7-5d330e776e69.gif)

**Comment by kidoln** [comment]
我知道了，我这里 C-enter, Alt-enter, Mac-enter，都可以实现补全前面的 +/-，但只有M-enter可以让输入法不变。另外两种，输入法都会变成英文。

我的问题解决了，多谢。

**Comment by laishulu** [comment]
@kidoln 

最新版已经可以在normal模式下<kbd>C-enter</kbd>，
新建item的时候自动切换输入法
https://emacs-china.org/t/native-os-sis/14089/57
