### ISSUE TITLE
advice 'smart-input-source--set-cursor-color-advice' override evil-mode cursor?

### ISSUE THREAD

**Issue by pRot0ta1p** [laishulu/emacs-smart-input-source#11]
evil-mode provided per mode cursor setting, it seems this package override it

In evil-mode:
```emacs-lisp
  (setq evil-insert-state-cursor '(bar "#00FF00")
		evil-visual-state-cursor '(box "#FF00FF")
		evil-normal-state-cursor '(box "#e2e8ef"))
```
the package didn't override cursor shape, but only the colors

**Comment by laishulu** [comment]
1. make sure you are using the latest version.
2. make sure you have not enabled `smart-input-source-cursor-color-mode`.

**Comment by pRot0ta1p** [comment]
This is wired...
Comment out (smart-input-source-global-cursor-color-mode t) will solve the issue however (smart-input-source-global-cursor-color-mode nil) still enable the advice...

**Comment by laishulu** [comment]
That's because you are using an old version, I am sure.
please see my fist advice.

**Comment by pRot0ta1p** [comment]
I'm using straight.el and the local repo is on the latest commit (9b4b7e183d725b70dd1d6853570d27fa57e544e4), I tried delete local files and pull the files again but till have the same problem... :confused: 

and here is my config:
```emacs-lisp
(use-package smart-input-source
  :straight (:depth full)
  :init
  (setq-default smart-input-source-english "xkb:us::eng"
				smart-input-source-other "rime")
  (setq-default smart-input-source-do-get
				(lambda()
				  (string-trim (shell-command-to-string
								(concat smart-input-source-external-ism " engine")))))
  (setq-default smart-input-source-do-set
				(lambda(source)
				  (string-trim (shell-command-to-string
								(concat smart-input-source-external-ism "ibus engine " source)))))
  (smart-input-source-global-cursor-color-mode nil)
  (smart-input-source-global-respect-mode t)
  (smart-input-source-global-follow-context-mode t)
  (smart-input-source-global-inline-mode t))
```

**Comment by laishulu** [comment]
`(smart-input-source-global-cursor-color-mode nil)`
should be deleted, or
`(smart-input-source-global-cursor-color-mode -1)`

`nil` still means turn on the mode.

**Comment by laishulu** [comment]
also, seems your `do-get` and `do-set` function are wrong.
please refer to the latest README.

**Comment by pRot0ta1p** [comment]
You are right, it should be -1. Thanks for the patient :heart:
