### ISSUE TITLE
Usage on Fedora Linux

### ISSUE THREAD

**Issue by oatmealm** [laishulu/emacs-smart-input-source#16]
Hi. I find it difficult to wrap my head around this. I understand the purpose is to be able to use non English keyboard layout at the OS level and still be able to type in Emacs without switching the os layout back to English first?

Also, does it work with other languages other than Chinese? Ie. On my system I need to switch between Hebrew, Arabic and English. 

I'm using fedora Linux with a snapshot version of Emacs pre 27.0. 

Thanks

**Comment by laishulu** [comment]
>I understand the purpose is to be able to use non English keyboard layout at the OS level and still be able to type in Emacs without switching the os layout back to English first?

Not exactly. 
It just **switch** input method (Emacs native input method or OS input method) automatically for you.
It has several modes, you can enable them as your need.

For example, if your current input method is Chinese, 
you want Emacs to switch to English automatically when minibuffer opens, 
and switch back to Chinese when minibuffer exit.

Or if you want to switch to English when exiting evil insert state,
and switch to English or Chinese according to your context.

>does it work with other languages other than Chinese

Yes, just set the corresponding patterns `sis-other-pattern`.

>On my system I need to switch between Hebrew, Arabic and English.

sis only support switch between english and other lanuage for a buffer,
but you can switch the `other` language can be different for different buffer.

**Comment by oatmealm** [comment]
Ok got it. Thank you!
