### ISSUE TITLE
cnfonts 下中英文混排的table不能对齐问题

### ISSUE THREAD

**Issue by kidoln** [laishulu/emacs-smart-input-source#18]
MacOS环境下，使用cnfonts配置，本来是可以实现中文或英文表格对齐的。
但是安装了smart-input-source后，由于它会在英文的前后自动添加空格，还不能手动删除。造成表格不能对齐了。具体见截图。
不太确定算不算是smart-input-source的问题，或者是否有快捷方式或命令，临时关闭自动添加空格在英文字符串的前后。
![image](https://user-images.githubusercontent.com/886552/89248889-62628c80-d643-11ea-9451-b76da8f4f8b7.png)

**Comment by laishulu** [comment]
> 由于它会在英文的前后自动添加空格，还不能手动删除

- 不会自动添加空格，sis的空格都是人手工输入进去的，
- 可以控制是否自动删除前后的空格。

>或者是否有快捷方式或命令，临时关闭自动添加空格在英文字符串的前后。

因为sis不会自动添加空格，如果你启用了inline-english的话，
下面的选项可以控制是否删除前后的空格，及删除多少前后的空格。
<img width="271" alt="图片" src="https://user-images.githubusercontent.com/1224321/89251502-c6884f00-d649-11ea-8f04-d780778a5496.png">

**Comment by laishulu** [comment]
@kidoln 
有进一步反馈么？
