### ISSUE TITLE
总是多出来一个字符

### ISSUE THREAD

**Issue by y8y** [laishulu/emacs-smart-input-source#20]
小概率出现这样的 bug，当我输入"abc"时，每个字符前面多了一个字母C，变成了"CaCbCc"。

![多出了一个字母](http://media.b4c.top/eb041290f12d17280e2160539564b116.jpg)

**Comment by laishulu** [comment]
代码里面没有强加`C`的部分。<br>
sis禁用之后，就不会出这个现象了么？

**Comment by y8y** [comment]
1. 没有强加 C，实际上，每次出bug的时候，这个字母不是固定的，比如上一次是C，我重启 Emacs 后，操作一段时间后多出来的字母可能是m；
2. 禁用 sis 后，没有出现这个现象。

**Comment by y8y** [comment]
重现的机制如下：
![](http://media.b4c.top/ba8e3e665b8013e5fa1503e3d792f88f.jpg)

**Comment by y8y** [comment]
emacs-plus有这个问题，我切换到 EMP(emacsmacport)后，这个问题就没有了。应该和特定的发现版本有关。
