### ISSUE TITLE
如何关闭智能识别？

### ISSUE THREAD

**Issue by Greapi** [laishulu/emacs-smart-input-source#21]
我现在有如下对应用场景：
```
进入插入模式------>使用中文输入法（无论上文是英文还是中文）
退出插入模式------>使用英文输入法
```
我没有找到相关的配置，请问这个功能要如何实现？ 谢谢

**Comment by laishulu** [comment]
智能识别是follow-context-mode提供的功能，
你可以设置 `sis-follow-context-fixed` 为 `'other`(非英语）。

**Comment by laishulu** [comment]
fixed意思是，固定context为`'other`，而不是根据上下文自己识别。
