### ISSUE TITLE
Error running timer 'sis--auto-refresh-timer-function':(text-read-only)

### ISSUE THREAD

**Issue by Aloxaf** [laishulu/emacs-smart-input-source#22]
我这里用 telega 的时候有时会报这个错，然后这个错误会频繁打断我的快捷键，连退出也退出不了，只能 kill 掉。

请教一下这个函数是用来干嘛的

emacs 版本：native-comp 分支最新版

**Comment by laishulu** [comment]
这个信息不全，我这里也不用telega，所以不好调试。
你在emacs中跑一下：
```
(setq debug-on-error t)
```
完了出现问题的时候，把message buffer中的信息贴出来我看看。

**Comment by Aloxaf** [comment]
当时试过了没反应
甚至直接点 X 退出都没反应

我下次遇到这个 bug 的时候再试试（其实有点怀疑是不是 native-comp 的锅……

**Comment by Aloxaf** [comment]
又出现了，注意到还有一个 `Error running timer ‘helm-ff--cache-mode-refresh’: (text-read-only)` 的错误

设置了 debug-on-error 也没反映，我估计应该不是 sis 的锅，打扰了

![图片](https://user-images.githubusercontent.com/17017672/94273948-a99c3800-ff77-11ea-80e6-0e0e29438b28.png)

**Comment by laishulu** [comment]
你这个内存使用，有点吓人。

**Comment by Aloxaf** [comment]
> 你这个内存使用，有点吓人。

我估计是这个 bug 导致的，我就只开了一个 telega……（难道是 telega 的锅？
