### ISSUE TITLE
Customize `sis-inline-face`

### ISSUE THREAD

**Issue by AnikaSU** [laishulu/emacs-smart-input-source#26]
Is there a way to costomize `sis-inline-face` ? `C-h ⅴ` showed no corresponding variables in doom emacs

**Comment by laishulu** [comment]
<kbd>M-x</kbd>，<br>
然后`describe-symbol` (即：<kbd> SPC h o</kbd>)<br>
或者`describe-face`(即：<kbd> SPC h F</kbd>)里面都有。

`sis-inline-face` 不是variable。

![Snipaste_2020-11-27_13-50-43](https://user-images.githubusercontent.com/1224321/100415834-002d0c00-30b8-11eb-8cd8-8936f401119d.jpg)

**Comment by AnikaSU** [comment]
配置成功了, 多谢!
