### ISSUE TITLE
emacsGUI和终端都只能中文切换成英文，无法英文切换成中文

### ISSUE THREAD

**Issue by lewisliuyi** [laishulu/emacs-smart-input-source#27]
使用环境：emacs-plus，终端检测结果：
~ % macism                                   
com.apple.inputmethod.SCIM.ITABC

~ % macism "com.apple.inputmethod.SCIM.ITABC"
Fatal error: Unexpectedly found nil while unwrapping an Optional value: file macism/macism.swift, line 80
zsh: trace trap  macism "com.apple.inputmethod.SCIM.ITABC"

**Comment by lewisliuyi** [comment]
上面是在终端中的输入命令和输出结果，如果我在中文模式下使用macism，则可以顺利切换成英文，反过来从英文切换成中文就会在状态栏那里闪一下报错

**Comment by laishulu** [comment]
这个是因为macism未能正常工作。<br>
你这样：
1. 重新brew安装macism
2. 确保已经正常授权。

中文切英文，是不需要特殊授权的。<br>
但是英文切中文，是需要你在MacOS中显式授权一次的。<br>
正常的话，你运行macism，MacOS会自动弹出授权对话框，<br>
如果没有的话，那你就需要手动授权了。

见：https://github.com/laishulu/macism

**Comment by lewisliuyi** [comment]
我已经在安全性隐私那里进行过授权了，但我会尝试重新安装一下，谢谢您的神奇作品

**Comment by laishulu** [comment]
闪一下报错，还有一个可能，是默认的delay值不合适，老旧的电脑比较容易出现。
见readme：
>macism SOME_INPUT_SOURCE_ID uSECONDS will select to SOME_INPUT_SOURCE_ID. If switch from none-CJKV to CJKV, will sleep uSECONDS (default to 20000) micro seconds.

你可以试试增大这个值。

**Comment by lewisliuyi** [comment]
在提交issue之前已经试过了，难道是因为我用的是m1芯片的macbook不兼容吗

**Comment by laishulu** [comment]
那也有可能？
毕竟你这个是新电脑，不存在性能问题。
我手头没有m1的系统，没法测试。

实在不行的话，你用emacs mac port
那个GUI下不需要外部切换工具，是native api 切换的

**Comment by laishulu** [comment]
不过，macism没有牵涉到驱动啊，硬件啊什么的，
理论上来讲，不应该出现兼容性问题的，
我这里macOS也是Big Sur，OS版本和你是一样的。

**Comment by laishulu** [comment]
哦，对了，你macOS里面，
切换上一个输入法的快捷键，
这个设置有么？

如果没有的话，
那就会出现你的那个错误

<img width="668" alt="图片" src="https://user-images.githubusercontent.com/1224321/104300399-62738c00-5501-11eb-8935-90cffc0c2fd6.png">

**Comment by laishulu** [comment]
快捷键可以和我设置的不一样，但必须得有，
代码里面是读取你的快捷键，然后模拟按键。

**Comment by laishulu** [comment]
@lewisliuyi Any feedback?

**Comment by lewisliuyi** [comment]
啊，我昨天已经提交了反馈，可能网络卡了交上？我昨天按照您的建议brew重装了您1.3.0版本的macism就能用了；然后我也额外试了emacsmacport，可以不依赖macism直接使用sis。在arm架构的m1芯片上，sis都可以使用

**Comment by lewisliuyi** [comment]
谢谢您的作品，很神奇，我用法只掌握了一小部分，还在摸索中

**Comment by lewisliuyi** [comment]
昨天的bug可能来源于brew install macism的版本是1.2.2的，这个版本在arm上有问题

**Comment by laishulu** [comment]
@lewisliuyi 

有用法上的问题，可以去这里问：

https://emacs-china.org/t/native-os-sis/14089
