### ISSUE TITLE
sis-global-respect-mode break magit-log-select-mode keybindings hint

### ISSUE THREAD

**Issue by tshu-w** [laishulu/emacs-smart-input-source#28]
to enter magit-log-select-mode, M-x magit-status, magit-rebase and select modify a commit
before enable it:
<img width="1298" alt="Screen Shot 2021-01-17 at 4 36 47 PM" src="https://user-images.githubusercontent.com/13161779/104835511-39c50b00-58e2-11eb-8d6b-b891d9b4b252.png">
after:
<img width="1304" alt="Screen Shot 2021-01-17 at 4 36 29 PM" src="https://user-images.githubusercontent.com/13161779/104835515-40ec1900-58e2-11eb-9bc8-bbcb8c787f20.png">

**Comment by liebkne** [comment]
开启了几个sis-*-mode之后，经常在magit buffer里自定义的快捷键会失效，比如：global-map里的`C-c f`绑定为`counsel-recentf`。有时`magit-status`在用着用着之后，这个快捷键（和其它一些绑定的global快捷键）就会失效了，然后过一会（不知道是不是又按了什么）又可以。

不知道与这个issue是否相关。

**Comment by laishulu** [comment]
@tshu-w 
那个magit log的buffer叫什么名字？
在你的配置中，参照下面这一行配置一下
https://github.com/laishulu/emacs-smart-input-source/blob/f2d4031711714b100ec81aac321917c40cf20dc9/sis.el#L846

这样可以disable前缀截取
请测试反馈

**Comment by laishulu** [comment]
> 开启了几个sis-*-mode之后，经常在magit buffer里自定义的快捷键会失效，比如：global-map里的`C-c f`绑定为`counsel-recentf`。有时`magit-status`在用着用着之后，这个快捷键（和其它一些绑定的global快捷键）就会失效了，然后过一会（不知道是不是又按了什么）又可以。
> 
> 不知道与这个issue是否相关。

要不，彻底把`magit`相关的buffer都disable快捷键前缀截取？
配置变量`sis-prefix-override-buffer-disable-predicates`
还是参见这一行的配置，"^magit-revision:"改成`"^magit"。
https://github.com/laishulu/emacs-smart-input-source/blob/f2d4031711714b100ec81aac321917c40cf20dc9/sis.el#L846

**Comment by laishulu** [comment]
因为我用的doom，
并不清楚原生emacs键位用户
在magit相关的buffer有没有按下<kbd>C-c</kbd>后自动切到英文输入法的需求。
所以，当时只是把magit-revision给加进去了

**Comment by laishulu** [comment]
> to enter magit-log-select-mode, M-x magit-status, magit-rebase and select modify a commit
> before enable it:
> <img alt="Screen Shot 2021-01-17 at 4 36 47 PM" width="1298" src="https://user-images.githubusercontent.com/13161779/104835511-39c50b00-58e2-11eb-8d6b-b891d9b4b252.png">
> after:
> <img alt="Screen Shot 2021-01-17 at 4 36 29 PM" width="1304" src="https://user-images.githubusercontent.com/13161779/104835515-40ec1900-58e2-11eb-9bc8-bbcb8c787f20.png">

看起来，快捷键发生改变了啊。。。
之前是<kbd>C-c C-c</kbd>，后来变成<kbd>e</kbd>了？
sis本身并不会改变快捷键，只是重定向快捷键绑定的函数。
所以，这个就很诡异了~~

**Comment by liebkne** [comment]
改成了`^magit`，因为之前也不是百分百出现，所以只能说现在还没有出现问题。基本上，除了写commit message的时候，都不会用到输入法……

**Comment by tshu-w** [comment]
> 看起来，快捷键发生改变了啊。。。
> 之前是C-c C-c，后来变成e了？
> sis本身并不会改变快捷键，只是重定向快捷键绑定的函数。
> 所以，这个就很诡异了~~

其实也没有改变快捷键，`magit-log-select-pick` 被绑定到了 `C-c C-c` 和 `e`，只是 `magit-log-select-quit` 也被绑定到了 `q` 却没有显示。

> 还是参见这一行的配置，"^magit-revision:"改成`"^magit"。

我直接到包里面改成了 `^magit` 不行。

最小可复现配置：

```emacs-lisp
;;; emacs -Q -l ~/.emacs.d/init.el

(setq package-archives '(("melpa" . "https://melpa.org/packages/")
                         ("org"   . "https://orgmode.org/elpa/")
                         ("gnu"   . "https://elpa.gnu.org/packages/")))

;; initialize packages
(unless (bound-and-true-p package--initialized) ; To avoid warnings in 27
  (setq package-enable-at-startup nil)          ; To prevent initializing twice
  (package-initialize))

;; setup `use-package'
(unless (package-installed-p 'use-package)
  (when (not package-archive-contents)
    (package-refresh-contents))
  (package-install 'use-package))

(require 'use-package)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(use-package evil
  :ensure t
  :init
  (setq evil-want-keybinding nil)
  (evil-mode))

(use-package evil-collection
  :ensure t
  :init
  (evil-collection-init))

(use-package magit :ensure t)

(use-package sis
  :ensure t
  :hook (after-init . sis-global-respect-mode)
  :config
  (sis-ism-lazyman-config nil "rime" 'native)

  (setq sis-prefix-override-keys '("C-c" "C-x" "C-h" "M-SPC"))

  (setq-default sis-inline-tighten-head-rule 0
                sis-inline-tighten-tail-rule 1))
```

不过有个问题很诡异，
`emacs -Q -l ~/.emacs.d/init.el` 是正常的，去掉 `-Q` 才会有上面的问题 `emacs -l ~/.emacs.d/init.el`

**Comment by Eason0210** [comment]
@laishulu  我也遇到了类似的问题。

执行 `magit-status` (C-x g ) 后，如果光标在 unstaged changes 下面，就没法执行 `C-x b`，` C-x 1` 等按键，提示按键未定义

```
C-x b is undefined 
```
光标在这个位置就不正常：

<img width="288" alt="image" src="https://user-images.githubusercontent.com/47546452/160967274-cd629d1f-26b7-4c67-88d2-5af9a662b60b.png">

光标在这个位置的时候正常：

<img width="222" alt="image" src="https://user-images.githubusercontent.com/47546452/160967589-604b9f1e-8032-402d-aebd-bece720e1c0d.png">

关闭 sis-global-respect-mode 后，都正常。
