### ISSUE TITLE
当Complete Mode自动补全之后，sis双拼输入会重复出现某一字符

### ISSUE THREAD

**Issue by chxin** [laishulu/emacs-smart-input-source#29]
问题描述：当使用中文双拼输入法，在输入过程中，出现中文或者英文的自动提示后(complete mode)，有概率在每一次键盘输入时，自动添加一个特定字符，造成输入错误。
我可能描述的不太清楚，录屏如下：

操作系统：macOS Catalina 10.15.7
Emacs: emacs-plus@28
配置：
(use-package sis
    :defer nil
    :config
    (progn
        (sis-ism-lazyman-config
         "com.apple.keylayout.ABC"
         "com.apple.inputmethod.SCIM.Shuangpin"
         )
        (sis-global-cursor-color-mode t)
        (sis-global-respect-mode t)
        ;; (sis-global-follow-context-mode t)
        (sis-global-inline-mode t)
      ))

**Comment by chxin** [comment]
![sis-bug](https://user-images.githubusercontent.com/19690966/104981681-07cbba00-5a44-11eb-9678-e3a0f3efe8da.gif)

**Comment by laishulu** [comment]
你输入中文后，如何切到英文输入法的呢？
就是xxmxzxlx那一行，是怎么切的？

**Comment by laishulu** [comment]
如果不开sis的那个mode，有这个情况么？
emacs 28之后才出现这个情况的，还是27也有呢？

**Comment by laishulu** [comment]
另外，你用的是spacemacs么？

**Comment by chxin** [comment]
> 你输入中文后，如何切到英文输入法的呢？
> 就是xxmxzxlx那一行，是怎么切的？
英文的第一行，xxmxzxlx，是我输入了xmzl，直接回车的结果。
之后的英文，是我切换回英文输入法，第二行英文是输入aaaa，出现xaxaxaxa，之后分别是bbbb,cccc,dddd，都会在每个字母前加上x

**Comment by chxin** [comment]
> 如果不开sis的那个mode，有这个情况么？
> emacs 28之后才出现这个情况的，还是27也有呢？


不开sis，是没有这种情况的。
emacs 27我没有试过，不过我在Manjaro 的Emacs 27试过，也出现了。

另外一个信息不知道有没有帮助：我用全拼，没有出现过这种情况

**Comment by chxin** [comment]
> 另外，你用的是spacemacs么？

是的，spacemacs。没有用hybrid mode，用的是vim mode

**Comment by vinurs** [comment]
这个应该不是这个包的问题，应该是emacs自己的问题，emacs28以及native分支都会经常性出现这个问题，https://emacs-china.org/t/emacs/15430/34应该跟这个问题是一样的

**Comment by chxin** [comment]
我在macos上尝试了emacs-plus@27，一样的配置，没有出现这样的问题。猜测应该如 @vinurs 所说，是emacs28自己的问题。

**Comment by Jeff-avatar** [comment]
@chxin 这个问题再emacs28上有解决办法了吗？ 谢谢！超级厌烦的一个事情

**Comment by Jeff-avatar** [comment]
@laishulu 请问这个问题在emacs28上有啥解决办法了吗？

**Comment by Jeff-avatar** [comment]
@chxin @laishulu 我发现我把sis关掉只有，在emacs28上用搜狗也会出现同样的问题，只是出现频率似乎稍微低了一点。

**Comment by laishulu** [comment]
跟sis无关的话，那我就把这个issue关了。
