### ISSUE TITLE
sis 是如何判断中文字符的？

### ISSUE THREAD

**Issue by dwuggh** [laishulu/emacs-smart-input-source#34]
是通过判断此字符不是英文字符吗？如果我输入了其它utf-8字符，比如希腊字母ρ，那么sis也会自动切换至中文输入法。请问这是expected behaviour吗？
能否通过utf-8编码判断中文字符，或者有没有相关的配置选项？

**Comment by laishulu** [comment]
readme中的 "About language pattern"

**Comment by dwuggh** [comment]
好的，抱歉没仔细看readme
