### ISSUE TITLE
支持 meow 吗?

### ISSUE THREAD

**Issue by guidao** [laishulu/emacs-smart-input-source#35]
最近在使用狗哥的 https://github.com/DogLooksGood/meow
跟 evil 一样也是基于模式的。想问下 sis 支持 meow 吗？或者有比较容易的方式支持吗？

**Comment by laishulu** [comment]
看这里：https://emacs-china.org/t/os-smart-input-source/13436/995?u=goumao

以及后面的帖子

**Comment by guidao** [comment]
好的。多谢。
