### ISSUE TITLE
很丢人提个问题，我看大家都问高级问题，我是根本没用起来

### ISSUE THREAD

**Issue by FinallyFinancialFreedom** [laishulu/emacs-smart-input-source#36]
我是macos，官网装的emacs，但用的doom emacs，用的evil。所以装了macism，我在kitty里使用macism，要授权来着，但是emacs切换输入法根本没提示授权。不过我emacs也授权了的。
我理解，安装上sis后，就没必要再config.el里配什么了吧，我默认输入法跟sis的默认是一样的。
目前就是完全不生效，跟没装一样，但M-x有sis相关命令，相关命令好使的。
但像什么进emacs就自动切换英文，什么退出insert模式切换英文，全没有。

**Comment by laishulu** [comment]
你这个和我的环境一模一样。
macos/doom/macism/kitty.

不应该有问题的。

>emacs切换输入法根本没提示授权。

macos的授权是看app文件的，
所以，你在kitty里面用macism，需要的是kitty的授权，不是emacs的授权。

>安装上sis后，就没必要再config.el里配什么了吧
不行啊，你是emacs新手么？
sis你必须use package才行的。

因为你和我的环境一模一样，
你可以直接参见我的配置。

https://github.com/laishulu/conf/blob/master/emacs/doom/edit.el

**Comment by laishulu** [comment]
我刚把回复更新了一下，你打开这个issue的网页看最新版吧。
这里：
https://github.com/laishulu/emacs-smart-input-source/issues/36#issuecomment-894674601

**Comment by FinallyFinancialFreedom** [comment]
多谢，回的太快了。
emacs新手，主力vim，只是为org-mode用emacs。
我开始配（use-package xxx）了，但可能xxx的名字不对，所以报错，就给删了。
刚照抄 readme里的Configure，可以了。

**Comment by laishulu** [comment]
>主力vim

用evil的，基本上都是从vim逃过来的。

你可能需要这个：
https://github.com/laishulu/vim-macos-ime

替代你正在使用的这个：
https://github.com/FinallyFinancialFreedom/fcitx-vim-osx

**Comment by FinallyFinancialFreedom** [comment]
赞，正找替换呢，多谢我试试去

**Comment by laishulu** [comment]
基于macism的。

那个vim插件很简单，关键是macism解决问题。
