### ISSUE TITLE
How to change the cursor default colour?

### ISSUE THREAD

**Issue by mrfengguan** [laishulu/emacs-smart-input-source#41]
Hi, How can I change the default cursor colour ?
I find a clue `sis-default-cursor-color` at here:
https://github.com/laishulu/emacs-smart-input-source/blob/237fb7029fde7c16a24d2231754d95190c1f03cd/sis.el#L68

Where is 'sis.el' installed? I can't find it in my MacOS by `rg sis-default-cursor-color`
Or any better approach like overwrite in config.el of Doom-emacs?
Thanks for creating this tool, it helps :)

The current default colour for English (the right window) is a bit too dark for me.
![image](https://user-images.githubusercontent.com/95098546/144493353-efcf90d3-c76b-4b00-8aaf-e75b17e73d3b.png)

**Comment by laishulu** [comment]
readme里面有，中英问状态下的光标颜色都可以设置。
进入这个页面：https://github.com/laishulu/emacs-smart-input-source
在页面上搜索：About cursor color mode

我也用的是doom emacs，
你可以参考一下我的emacs配置的结构
https://github.com/laishulu/conf/tree/master/emacs/doom

**Comment by mrfengguan** [comment]
Thanks for the explanation.

I tried to followed the README, but after adding the line in the `config.el`
```
  (sis-default-cursor-color "white") 
```

It pops an error.  Maybe I used it in a wrong way, what should I do? Thanks.

In config.el
![image](https://user-images.githubusercontent.com/95098546/144653322-f24e3605-a799-4a77-961b-5541e3c98811.png)

The error info in debug mode
![image](https://user-images.githubusercontent.com/95098546/144653340-021e3108-44b7-4d9f-bd72-1008c6f75f88.png)

**Comment by laishulu** [comment]
你真的是emacs小白啊。。
这个是变量，不是函数。
```
(setq sis-default-cursor-color "white") 
```

**Comment by mrfengguan** [comment]
```(setq sis-default-cursor-color "white") ```  works. Thanks.

How to distinguish which is value, which is function?
`sis-default-cursor-color`
`sis-global-cursor-color-mode`

**Comment by laishulu** [comment]
你用的doom吧。
<img width="233" alt="Snipaste_2021-12-05_22-14-54" src="https://user-images.githubusercontent.com/1224321/144750289-36fd7bf7-78c2-4401-8b23-8d03a7f4202e.png">

<kbd>M-x</kbd>(MacOS下是<kbd>Option x</kbd>),
然后输入 `describe-symbol`命令。

或者<kbd>Space h o</kbd>

**Comment by mrfengguan** [comment]
> M-x(MacOS下是Option x), 然后输入 `describe-symbol`命令。
Cool 👍
