### ISSUE TITLE
sis和mac上鼠须管的协同问题

### ISSUE THREAD

**Issue by whjiang** [laishulu/emacs-smart-input-source#44]
中文输入后，切到Normal mode，再切回到insert mode时，鼠须管会是英文输入，要多按下SHIFT才能切成中文。用搜狗作为中文输入就没有这个问题。

从 https://github.com/rime/squirrel/issues/85 和 https://github.com/rime/squirrel/issues/179#issuecomment-364048969 来看，是RIME和MAC的兼容性问题。

看emacs-rime是通过定义
```
(defun rime--inline-ascii ()
  "Toggle inline ascii."
  (let ((key-code
         (cl-case rime-inline-ascii-trigger
           (shift-l 65505)
           (shift-r 65506)
           (control-l 65507)
           (control-r 65508)
           (alt-l 65513)
           (alt-r 65514))))
    (rime-lib-process-key key-code 0)
    (rime-lib-process-key key-code 1073741824)))
```
在切换到rime后，向rime发送shift键来切换回中文。

不知道SIS是不是可以做类似的事情，向鼠须管发送shift键，来自动切换回中文。

**Comment by fu123456** [comment]
> 中文输入后，切到Normal mode，再切回到insert mode时，鼠须管会是英文输入，要多按下SHIFT才能切成中文。用搜狗作为中文输入就没有这个问题。
> 
> 从 [rime/squirrel#85](https://github.com/rime/squirrel/issues/85) 和 [rime/squirrel#179 (comment)](https://github.com/rime/squirrel/issues/179#issuecomment-364048969) 来看，是RIME和MAC的兼容性问题。
> 
> 看emacs-rime是通过定义
> 
> ```
> (defun rime--inline-ascii ()
>   "Toggle inline ascii."
>   (let ((key-code
>          (cl-case rime-inline-ascii-trigger
>            (shift-l 65505)
>            (shift-r 65506)
>            (control-l 65507)
>            (control-r 65508)
>            (alt-l 65513)
>            (alt-r 65514))))
>     (rime-lib-process-key key-code 0)
>     (rime-lib-process-key key-code 1073741824)))
> ```
> 
> 在切换到rime后，向rime发送shift键来切换回中文。
> 
> 不知道SIS是不是可以做类似的事情，向鼠须管发送shift键，来自动切换回中文。

我也遇到类似的问题，就是使用C-\切换到中文输入法的时候，还需要再按下Shift才可以正确切换到中文输入。我使用的是emacs-mac 29.

**Comment by fu123456** [comment]
有配置代码吗？
