### ISSUE TITLE
"SPC SPC" 变成了". SPC"

### ISSUE THREAD

**Issue by whjiang** [laishulu/emacs-smart-input-source#45]
在中文后（当前输入法也是中文输入法），按 "SPC SPC"，预期进入临时英文模式输入，但实际是输入了“. SPC”，自动把输入法也切换成英文了。

**Comment by whjiang** [comment]
我的emacs是mac port 27.2

**Comment by laishulu** [comment]
你“. SPC”是什么意思，我也不清楚。
你可以截屏贴过来看看，gif动画更好。

另，可用一个只含有sis的最小环境测试一下，
有可能是你的环境中其它package的作用。

你是第一次试用这个功能，
还是说你那边之前正常，现在出了问题？

**Comment by suliveevil** [comment]
是不是没有关掉系统的“连按两下空格输入句号”？

**Comment by laishulu** [comment]
<img width="668" alt="Snipaste_2022-09-23_17-21-50" src="https://user-images.githubusercontent.com/1224321/191930456-e1ea16ab-d20c-43e3-8282-9b48211c6b57.png">
