### ISSUE TITLE
常用中文输入,问题

### ISSUE THREAD

**Issue by dian-yu-luo** [laishulu/emacs-smart-input-source#46]
请问如果我是中文输入,希望进入在从evil的normal模式退出到insert模式是,我希望获得和原来一直的输入法,
比如 原理是中文就 用中文的 输入, 原来是英文就用英文
另外我发现我只要进行一些配置,比如在use-package 后面加一个绑定 ,就导致了我的sis配置失效了

**Comment by dian-yu-luo** [comment]
环境 Windows + im-select

**Comment by dian-yu-luo** [comment]
对了,或者就写死,进入insert模式我要 中文输入,如果可以,怎么配置

**Comment by laishulu** [comment]
https://emacs-china.org/t/native-os-sis/14089/45

见这里

**Comment by dian-yu-luo** [comment]
可以自定义判断条件吗,比如 当 当前mode是org-mode ,当前光标位置是org heading 这个时候进入insert 是中文,其他的按照 sis-context-mode的规则来
