### ISSUE TITLE
和 fcitx.el 做个对比

### ISSUE THREAD

**Issue by QiangF** [laishulu/emacs-smart-input-source#5]
有没有两个都用过的呀
https://github.com/cute-jumper/fcitx.el

**Comment by laishulu** [comment]
自己看一下特性对比吧~~~

**Comment by QiangF** [comment]
好像用系统输入法，有时也出现例外的情况：按键貌似是先通过输入法处理一遍，要完美支持所有的规则只有
https://github.com/DogLooksGood/emacs-rime

**Comment by laishulu** [comment]
emacs-rime是嵌入到emacs的输入法，
smart-input-source是用的操作系统输入法。
根据用户反馈，smart-input-source  已经很完善了，
内置输入法做到的事情，目前smart-input-source都做到了。

**Comment by QiangF** [comment]
嗯，fcitx.el 不能 Respect buffer: recover buffer input source when it regain focus.

**Comment by QiangF** [comment]
感觉你这个更胜一筹！
