### ISSUE TITLE
wsl2 下使用 fcitx 作为输入法输入中文，fcitx-remote 指令不生效

### ISSUE THREAD

**Issue by ray2011** [laishulu/emacs-smart-input-source#53]
![image](https://user-images.githubusercontent.com/7893714/174743352-78438baf-aac5-4a3f-9098-6a67f2bbad41.png)
没啥思路，作者有什么建议吗

**Comment by laishulu** [comment]
早就解决了吧。。。

https://github.com/laishulu/emacs-smart-input-source/blob/c1995854f57cf231e4484d7bec1dd6c5953d09ec/sis.el#L524

**Comment by laishulu** [comment]
哦，不对。这里是在WSL里面用im-select的。不是用的fcitx

**Comment by laishulu** [comment]
不过这个和sis没有关系，得去linux社区寻找答案了。

我也不知道。我日常系统是MacOS。
