### ISSUE TITLE
如何临时切换

### ISSUE THREAD

**Issue by dian-yu-luo** [laishulu/emacs-smart-input-source#57]
我希望在仅仅某个函数打开buffer等待候选的时候切换中英文,例如在org-roam中定制如下
的函数,但是却没有切换输入法

``` elisp
  (global-set-key (kbd "C-c n n")
                  '(lambda()
                     (interactive)
                     (org-roam-node-find)
                     (sis-set-other)))

```

**Comment by laishulu** [comment]
>某个函数打开buffer等待候选

这个是什么意思？

**Comment by dian-yu-luo** [comment]
举个例子,我是org-roam用户,我想创建一个节点 采用如下函数 org-roam-node-find,打开一个minibuffer,这个时候就切换到英文输入法.
如果我想创建一个中文节点,我就要手动切换输入法(windows 使用组合键 ctrl+space),但是我不想额外动这一下,我想直接写个函数,可以创建中文org-roam-node,也就是打开minibuffer这个时候就是中文输入法

**Comment by dian-yu-luo** [comment]
> 

就是打开minibuffer之后,光标在这里
![图片](https://user-images.githubusercontent.com/58965094/222939583-71c34953-16c5-4767-b63c-8af6e5eead1b.png)
这个时候输入法是英文的,我想让我改成中文的

**Comment by laishulu** [comment]
见这里：

https://github.com/laishulu/emacs-smart-input-source/blob/e4142baa470e5f33dd508bce0264359dc5204b6f/sis.el#L96

这个功能很久之前就加上了，
我怀疑当初就是你提的需求
毕竟这个需求很小众😂

你试试，
看看是不是你需要的功能，
并在这个issue里面反馈。

**Comment by laishulu** [comment]
其实还可以玩得更花一些。
比如当前光标下的上下文是中文，或者当前node的title是中文，
则`org-roam-node-find`打开的时候自动切换到中文。
都可以通过定制那个lambda函数实现。

**Comment by dian-yu-luo** [comment]
感谢您的帮助
