### ISSUE TITLE
Mac M1 不能切换rime

### ISSUE THREAD

**Issue by Jousimies** [laishulu/emacs-smart-input-source#58]
终端执行 `macism im.rime.inputmethod.Squirrel.Rime` 提示如下
macism/macism.swift:80: Fatal error: Unexpectedly found nil while unwrapping an Optional value
[1]    1493 trace trap  macism im.rime.inputmethod.Squirrel.Rime

但是执行 `macism com.apple.keylayout.ABC`可以切换到英文输入法。

**Comment by laishulu** [comment]
https://github.com/laishulu/macism/issues/5
