### ISSUE TITLE
如何跨行检测当前光标之前的两个单词？感谢感谢 🙏

### ISSUE THREAD

**Issue by suliveevil** [laishulu/emacs-smart-input-source#59]
这样的话就能减少中英文切换次数，行内插入单个英文单词也不会影响输入法状态，以及不需要在中文输入法下按两次空格插入一个空格了。

## 相关讨论

中文空格：

https://github.com/laishulu/emacs-smart-input-source/issues/7

探针：

https://github.com/tumashu/pyim/issues/463

Keyboard Maestro 实现在 macOS 上的两个单词的检测，方法很笨，效率很低：

https://forum.keyboardmaestro.com/t/input-monitor-text-selection-and-character-before-the-cursor/26567

**Comment by suliveevil** [comment]
写了个简单的正则匹配，不知道怎么用 elisp 实现

```regexp
(([\u2e80-\u9fff]+)([\n\r]{1,2})?([\s\t])?(([\u2e80-\u9fff]+)|(\w)+)([\s\t])?)
```


<img width="805" alt="跨行检测两个单词是否含有中文" src="https://user-images.githubusercontent.com/35763237/211178943-00612bf4-ab3f-43a1-84a1-3e1d1c84f719.png">

**Comment by suliveevil** [comment]
智能的代价就是更麻烦吧，算了，我先放弃了。

**Comment by laishulu** [comment]
不要自己弄啊，不可靠，容易有edge case，最好是调用emacs自己的功能。
记下当前的cursor，然后调用backward-word函数，再调用current-word获得当前的word，都完成之后光标复原。
大概相当于下面这样：

```
  (save-excursion
    (backward-word)
    (setq word1 (current-word)
    (backward-word)
    (setq word2 (current-word))
```

**Comment by laishulu** [comment]
sis中类似代码：

https://github.com/laishulu/emacs-smart-input-source/blob/02777a46a4b7c18c2cd588e6e2f11e83ba2378e4/sis.el#L1152

**Comment by suliveevil** [comment]
🤣 我水平太差了，我先学学基本语法再尝试添加 detect-word 吧。

感谢。
