### ISSUE TITLE
支持 program mode 只在 comment 和 string 中间输入中文

### ISSUE THREAD

**Issue by QiangF** [laishulu/emacs-smart-input-source#6]
别的地方看到的函数

    (defun mixed-context-p ()
    "当前为`prog-mode'或`conf-mode'，且光标在注释或字符串当中。"
    (when (derived-mode-p 'prog-mode 'conf-mode)
        (not (or (nth 3 (syntax-ppss))
                (nth 4 (syntax-ppss))))))

**Comment by laishulu** [comment]
好主意！我今天给放进去。

**Comment by QiangF** [comment]
当前program mode好像有个缺陷，evil mode 开的情况，insert mode 输入中文，然后ESC切换到 normal mode，再切换到 insert mode，就变成英文输入状态了，如果是 text mode 还是中文状态。

**Comment by laishulu** [comment]
仔细考虑了一下，只在 comment 和 string 中间输入中文 ，还是不用加了。
因为没有必要。

`smart-input-source-follow-context-mode` 原本就是在英文上下文中不会切换成中文。
所以，在comment 和 string之外，本来也不会自动切换成中文。

**Comment by QiangF** [comment]
好像不是这样，比如 python mode，我单起一行，中文输入法下输入1，2，逗号就是全角字符。

需求场景应该是字符串和comment中有中文，如果离开这些区域忘记切换回来，比如python mode，中英文+, ，不容易分辨，造成语法错误。

**Comment by QiangF** [comment]
当前program mode好像有个缺陷：evil mode 开的情况，insert mode 输入中文，然后ESC切换到 normal mode，再切换回来到 insert mode，就变成英文输入状态了，没有记忆之前的输入法状态，如果是 text mode buffer, 回来后还是中文状态。

**Comment by QiangF** [comment]
不过好像没必要在program mode非字符和comment中开中文输入法。

**Comment by laishulu** [comment]
`再切换到 insert mode，就变成英文输入状态` 
这个是 `smart-input-source-follow-context-mode` 决定的。
如果上下文是英文，就自动切换成英文状态。
如果上下文是中文，就自动切换成中文状态。
并不记忆离开insert模式之前的输入法状态。
