### ISSUE TITLE
空格自动中英切换问题

### ISSUE THREAD

**Issue by QiangF** [laishulu/emacs-smart-input-source#7]
中文字符后接空格，自动切到英文，之后的英文后空格，第一个中文字符后空格被删除了，感觉不妥，应该保留。

**Comment by laishulu** [comment]
这种方式，可以在不显示切换输入法的情况下，
仅仅靠空格和回车，
实现 `中文 english  中文` 和 `中文english中文`.

**Comment by QiangF** [comment]
嗯 好像实现的是
实现 中文english 中文 和 中文english中文.

**Comment by laishulu** [comment]
这两种，用户都是需要的，各有所好。

**Comment by QiangF** [comment]
哦 明白了，两个空格就可以保留那个空格了。

**Comment by laishulu** [comment]
`中文<spc><spc>english<spc><spc>中文`，就可以得到 `中文 English 中文`
