### ISSUE TITLE
当切换主题后,  sis-default-cursor-color 应当更新.

### ISSUE THREAD

**Issue by unifreak** [laishulu/emacs-smart-input-source#78]
现在的 sis-default-cursor-color 在第一次从当前主题拿到值后, 就定下来不会变了. 如果此时切换到另一个主题 (比如从亮色主题切到了暗色主题), 旧的光标颜色, 大概率是很难在新主题中有比较好的显示效果的.

Emacs 没有内置的主题切换相关的 hook, 我现在是通过下面的方式, 绕过了这个问题:

```elisp
;; taken from:
;; https://www.gnu.org/software/emacs/manual/html_node/modus-themes/A-theme_002dagnostic-hook-for-theme-loading.html
;; (sis need this to reset default cursor color after theme change)
(defvar after-enable-theme-hook nil
   "Normal hook run after enabling a theme.")

(defun run-after-enable-theme-hook (&rest _args)
   "Run `after-enable-theme-hook'."
   (run-hooks 'after-enable-theme-hook))

(advice-add 'enable-theme :after #'run-after-enable-theme-hook)

;; input method
(use-package sis
  :config
  (defun reset-sis-cursor-color ()
    "Reset sis cursor color to nil, to trigger updates after theme change"
    (setq sis-default-cursor-color nil))
  (add-hook 'after-enable-theme-hook 'reset-sis-cursor-color)) 
```

希望能在 sis 内部解决这个 bug, 这样就不需要这个 hack 了.

**Comment by Eason0210** [comment]
目前最近的 commit会造成我的主题加载时提示错误。

<img width="754" alt="image" src="https://github.com/user-attachments/assets/8daefb38-fa7d-45b4-8b31-74c0fa7fb49c" />

经过二分查找，是 [c538577](https://github.com/laishulu/emacs-smart-input-source/commit/c538577ae08708217dac92677f2a16e89f397fe5) 这个 commit 造成的。

以下是我的主题设置：

https://github.com/Eason0210/.emacs.d/blob/master/init.el#L82-L106

**Comment by Eason0210** [comment]
> 应该是你前两天更新了，但后来没更新到最新版。 #81

我确认已经更新到了最新的commit：
https://github.com/laishulu/emacs-smart-input-source/commit/b83b8db

换主题时会提示这个：
```
Error setting custom-enabled-themes: (wrong-number-of-arguments (0 . 0) 1)
```

**Comment by Eason0210** [comment]
没问题了，谢谢！
