### ISSUE TITLE
Error in pre-command-hook when a dired buffer is left open and the file system is unmounted

### ISSUE THREAD

**Issue by QiangF** [laishulu/emacs-smart-input-source#9]
外置硬盘拔掉后遗留的buffer会导致无法执行一些快捷键。

**Comment by laishulu** [comment]
详细一点呢？
操作步骤说一下，包括：什么buffer，什么快捷键

**Comment by QiangF** [comment]
汗，貌似又变好了。如果在:config里开那几个mode会出第一个org mode buffer不起作用的问题，我把它们加到 after-init-hook 就好了。

    (use-package smart-input-source
    :init
    (require 'smart-input-source)
    (defun my-enable-smart-input-source ()
        (smart-input-source-global-respect-mode t)
        (smart-input-source-global-follow-context-mode t)
        (smart-input-source-global-inline-english-mode t))
    :hook (after-init . my-enable-smart-input-source))
